// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplateprst = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/example/{name}": {
            "get": {
                "description": "展示例子",
                "tags": [
                    "Example"
                ],
                "summary": "展示例子",
                "parameters": [
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/router.Respo"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "router.Respo": {
            "type": "object",
            "properties": {
                "info": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoprst holds exported Swagger Info so clients can modify it
var SwaggerInfoprst = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "prst API",
	Description:      "gin框架API",
	InfoInstanceName: "prst",
	SwaggerTemplate:  docTemplateprst,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoprst.InstanceName(), SwaggerInfoprst)
}
