definitions:
  core.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      requestId:
        type: string
    type: object
info:
  contact: {}
  description: gin框架API
  title: prst API
  version: 0.0.1
paths:
  /api/v1/example/{name}/{phone}:
    get:
      description: 展示例子
      parameters:
      - description: 名称
        in: path
        name: name
        type: string
      - description: 手机号
        in: path
        name: phone
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.Response'
      summary: 展示例子
      tags:
      - Example
swagger: "2.0"
